---
title: "Martelos do Sul"
subtitle: "Projeto de Tese de Doutorado"
author: "Mariano Cabanillas-Torpoco"
institute: "Laboratório de Dinâmica Populacional Pesqueira, IO-FURG"
date: "03/09/2024"
lang: pt-br
title-slide-attributes:
  data-background-color: "#6b5a59"
transition: 'concave'
format: 
  revealjs:
    theme: [sky, custom]
    footer: "Martelos do Sul"
    slide-number: true
    chalkboard: true #Muito bom para aula
    multiplex: false #Os alunos podem seguir com smartfone. ToDo.
    show-slide-number: all
    controls: true #Não é menu. ToDo.
    #Sem estes css o :::box não funciona
    css: [assets/syntax-highlight.css,assets/sydney.css, assets/custom.css,assets/sydney-fonts.css]
editor: visual
---

## Introdução

*Sphryna zygaena* e *S. lewini*, frequentemente capturadas por diversas frotas pesqueiras, são altamente vulneráveis à pesca devido ao seu lento crescimento populacional.   Existem lacunas de conhecimento sobre seus padrões de movimento vertical e horizontal, assim como o uso da área de estudo nas diferentes fases de vida. 



## Objetivo

O projeto visa analisar a distribuição espacial e temporal de *Sphryna zygaena* e *S. lewini* no Oceano Atlântico Equatorial e Sudoeste (AESO).


# Hipôtesis sugeridas

## Hipôtese 1
S. lewini tenha preferência por aguas mais cálidas por cima da termoclina durante o dia e realize imersões mais profundas durante a noite, enquanto S. zygaena se encontrará frequentemente em aguas superficiais e costeiras, evitando as aguas sob a termoclina 

## Hipôtese 2
Há diferenças na distribuição espacial potencial entre as duas espécies durante diferentes épocas do ano, com S. lewini procurando aguas cálidas em áreas oceânicas, especialmente na temporada fria, e S. zygaena ocupando áreas mais costeiras e superficiais, com potencial segregação por sexo e estágio de vida em ambas espécies  

## Hipôtese 3 
A abundancia relativa dessas espécies varia ao longo do ano influenciado por fatores como disponibilidade de presas, temperatura d’água e correntes oceânicas


## Metodos
Para superar estas lacunas serão implantados Pop-up Satellite Archival Tags (PSATs) em 5 indivíduos de cada espécie, cujos dados serão usados para reconstruir seus movimentos horizontais e verticais. Além disso, serão analisados dados de capturas por unidade de esforço de XXXXXX lances de pesca e comprimentos de XXXX indivíduos amostrados entre 1998 e 2024, nas águas jurisdicionais de Brasil e Uruguai, e nas águas internacionais do AESO.

## Contribuição do estudo

Espera-se que os resultados contribuam para estratégias de manejo sustentável e a conservação das espécies, baseadas em informações sobre o uso do hábitat nas diferentes fases de vida.
 <https://quarto.org/docs/presentations/>.

## Bullets

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Code

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```
